name: Deploy ngx-crumb-demo

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  pages: write

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.x

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Install dependencies
        run: pnpm install --prefer-offline --frozen-lockfile

      - name: Build
        run: pnpm build --configuration=production ngx-crumb-demo

      - name: Upload static files as artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist/ngx-crumb-demo/browser

      - name: Publish to GitHub Pages
        uses: actions/deploy-pages@v4
